name: Build and deploy to Azure Web App

env:
  COMMIT_SHA: ${{ github.sha }}
  MVN_USER: ${{ github.actor }}
  MVN_PCKGS: ${{ secrets.MVN_PCKGS }}
  GITHUB_USER: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.MVN_PCKGS }}
  PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish docker image
        run: nix develop --impure --command publishInfra
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ env.PULUMI_CONFIG_PASSPHRASE }}
          COMMIT_SHA: ${{ env.COMMIT_SHA }}
          MVN_PCKGS: ${{ env.MVN_PCKGS }}
          GITHUB_USER: ${{ env.GITHUB_USER}}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.KVALREG_AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.KVALREG_AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID_PROD }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.KVALREG_AZURE_SUBSCRIPTION_ID }}
          AZURE_STORAGE_ACCOUNT: oqr
          AZURE_STORAGE_KEY: ${{ secrets.OQR_PULUMI_BLOB_KEY }}
          DOCKER_REGISTRY_SERVER_PASSWORD:
            ${{ secrets.KVALREG_DOCKER_REGISTRY_SERVER_PASSWORD }}

